# Generated by Django 4.0.5 on 2022-08-06 16:35

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=500)),
                ('my_description', models.CharField(max_length=1000)),
                ('profile_pics', sorl.thumbnail.fields.ImageField(upload_to='about')),
                ('profile_details', models.CharField(max_length=1000)),
                ('skills_details', models.CharField(max_length=1000)),
                ('job', models.CharField(max_length=1000)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=500)),
                ('certificate', models.CharField(max_length=1000)),
            ],
        ),
    ]
