# Generated by Django 4.0.5 on 2022-08-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_company', models.CharField(max_length=500)),
                ('work_country', models.CharField(max_length=500)),
                ('work_position', models.CharField(max_length=500)),
                ('work_duration', models.CharField(max_length=500)),
                ('work_duity', models.CharField(max_length=500)),
            ],
        ),
    ]
