# Generated by Django 4.0.5 on 2022-08-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(max_length=500)),
                ('education_duration', models.CharField(max_length=500)),
                ('education_field', models.CharField(max_length=500)),
                ('education_description', models.CharField(max_length=500)),
            ],
        ),
    ]
