# Generated by Django 4.0.5 on 2022-08-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_educationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='email',
            field=models.EmailField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='phone_call',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='whatsapp_call',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
