# Generated by Django 4.0.5 on 2022-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
    ]
