# Generated by Django 4.0.5 on 2022-08-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='auth_token',
        ),
    ]
